In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# **Dates:**

In [2]:
data = pd.read_csv("orders.csv")
data.sample(5)

           date  product_id  city_id  orders
536  2019-04-24        1140       26       2
327  2019-03-26        6115       22      63
464  2018-09-26        4895       29       1
783  2019-08-11         582       26       3
774  2019-08-17        2459        0       8

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [4]:
data["date"] = pd.to_datetime(data["date"])

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [6]:
data.sample(5)

          date  product_id  city_id  orders
298 2018-12-12        3748       17      11
435 2018-10-20        4847       26       9
631 2019-06-30        4323        4       7
901 2019-07-24        7148       16       9
497 2018-11-26        4667        9       1

In [16]:
# Extract year, month and day
data["date_year"] = data["date"].dt.year
data["date_month"] = data["date"].dt.month
data["date_day"] = data["date"].dt.day

data.sample(5)

          date  product_id  city_id  orders  date_year  date_month  date_day
787 2019-07-19        5371       22       8       2019           7        19
430 2019-10-20        6336       23      13       2019          10        20
735 2018-12-20        1445        9      60       2018          12        20
665 2018-09-29         146       16       5       2018           9        29
25  2018-09-14        4487       14       1       2018           9        14

In [17]:
# Extract month name
data["date_month_name"] = data["date"].dt.month_name()

data.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name
433,2019-08-15,5770,14,1,2019,8,15,August
445,2019-10-14,4192,14,59,2019,10,14,October
644,2019-01-29,4065,16,1,2019,1,29,January
229,2019-11-29,4047,16,5,2019,11,29,November
198,2018-08-28,685,25,29,2018,8,28,August

In [19]:
# Extract time elapsed between todays date and data's dates

import datetime

dt_current = datetime.datetime.today()

dt_current

datetime.datetime(2026, 1, 3, 12, 30, 32, 541495)

In [20]:
dt_current - data["date"]

0     2216 days 12:30:32.541495
1     2698 days 12:30:32.541495
2     2629 days 12:30:32.541495
3     2331 days 12:30:32.541495
4     2554 days 12:30:32.541495
                 ...
995   2644 days 12:30:32.541495
996   2585 days 12:30:32.541495
997   2433 days 12:30:32.541495
998   2498 days 12:30:32.541495
999   2272 days 12:30:32.541495
Name: date, Length: 1000, dtype: timedelta64[ns]

In [22]:
(dt_current - data["date"]).dt.days

0      2216
1      2698
2      2629
3      2331
4      2554
       ...
995    2644
996    2585
997    2433
998    2498
999    2272
Name: date, Length: 1000, dtype: int64

# **Time**

In [32]:
data = pd.read_csv("messages.csv")

In [33]:
data.sample(5)

                    date                                                msg
730  2016-03-13 23:14:00         симп п30 пригл симп.дев в гости 0507423054
526  2015-08-01 23:39:00         Парень поцелует девушке  .... т.0971374973
187  2013-02-15 23:57:00  м 52 ищу не высокую ж для встреч днепр лев бер...
232  2014-05-14 00:29:00  одинокая женщина ищет тепло и любовь.если есть...
35   2015-10-27 01:07:00                             Парень 24. Ищу девушку

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [35]:
data["date"] = pd.to_datetime(data["date"])

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [37]:
data["date_hr"] = data["date"].dt.hour
data["date_min"] = data["date"].dt.minute
data["date_sec"] = data["date"].dt.second

data.sample(5)

,date,msg,date_hr,date_min,date_sec
756,2012-06-02 00:24:00,Девушки вам тоже скучно?:-( 096 310 62 45,0,24,0
548,2014-05-10 01:04:00,ищю дев-жен до40л для и/о п30л смс098 795 62 1...,1,4,0
615,2013-02-11 01:11:00,знакомлюсь с парнем. Я парень 28 лет. 0***,1,11,0
654,2013-08-08 02:09:00,заберу на машине девушек которые смелые ? кто ...,2,9,0
359,2015-12-24 00:47:00,Адекватный парень познакомиться с девушкой для...,0,47,0